/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gtanalysis_gtexcel_jni_StringFunctions */

#ifndef _Included_com_gtanalysis_gtexcel_jni_StringFunctions
#define _Included_com_gtanalysis_gtexcel_jni_StringFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gtanalysis_gtexcel_jni_StringFunctions
 * Method:    arrlength
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gtanalysis_gtexcel_jni_StringFunctions_arrlength
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
