
package com.gtanalysis.gtexcel.ui;

import com.gtanalysis.gtexcel.model.SortType;
import com.gtanalysis.gtexcel.model.listener.WorkbookEvent;
import com.gtanalysis.gtexcel.model.listener.WorkbookListener;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Anoop
 */
public class GTExcelMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form GTExcelMainPanel
     */
    public GTExcelMainPanel() {
        initComponents();
        initCustom();
    }
    public WorkbookPanel getWorkbookPanel() {
        return workbookPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainToolBar = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        undoRedoToolBarSeparator = new javax.swing.JToolBar.Separator();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        copyPasteToolBarSeparator = new javax.swing.JToolBar.Separator();
        copyButton = new javax.swing.JButton();
        cutButton = new javax.swing.JButton();
        pasteButton = new javax.swing.JButton();
        tableOperationsSeparator = new javax.swing.JToolBar.Separator();
        insertColumnButton = new javax.swing.JButton();
        insertRowButton = new javax.swing.JButton();
        removeColumnButton = new javax.swing.JButton();
        removeRowButton = new javax.swing.JButton();
        alignmentSeparator = new javax.swing.JToolBar.Separator();
        alignHorizontalLeftButton = new javax.swing.JButton();
        alignHorizontalCenterButton = new javax.swing.JButton();
        alignHorizontalRightButton = new javax.swing.JButton();
        alignVerticalTopButton = new javax.swing.JButton();
        alignVerticalMiddleButton = new javax.swing.JButton();
        alignVerticalBottomButton = new javax.swing.JButton();
        fontStyleSeparator = new javax.swing.JToolBar.Separator();
        styleBoldButton = new javax.swing.JButton();
        styleItalicButton = new javax.swing.JButton();
        styleUnderlineButton = new javax.swing.JButton();
        sortSeparator = new javax.swing.JToolBar.Separator();
        sortAscendingButton = new javax.swing.JButton();
        sortDescendingButton = new javax.swing.JButton();
        chartSeparator = new javax.swing.JToolBar.Separator();
        addChartButton = new javax.swing.JButton();
        editChartButton = new javax.swing.JButton();
        removeChartButton = new javax.swing.JButton();
        chartVisibilityToggleButton = new javax.swing.JToggleButton();
        workbookPanel = new com.gtanalysis.gtexcel.ui.WorkbookPanel();

        setLayout(new java.awt.GridBagLayout());

        mainToolBar.setFloatable(false);
        mainToolBar.setRollover(true);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/document-new-6.png"))); // NOI18N
        newButton.setToolTipText("New");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(newButton);

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/folder-green.png"))); // NOI18N
        openButton.setToolTipText("Open");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(openButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/document-save-5.png"))); // NOI18N
        saveButton.setToolTipText("Save");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(saveButton);
        mainToolBar.add(undoRedoToolBarSeparator);

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-undo-7.png"))); // NOI18N
        undoButton.setToolTipText("Insert Column");
        undoButton.setFocusable(false);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(undoButton);

        redoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-redo-7.png"))); // NOI18N
        redoButton.setToolTipText("Insert Column");
        redoButton.setFocusable(false);
        redoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(redoButton);
        mainToolBar.add(copyPasteToolBarSeparator);

        copyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-copy-3.png"))); // NOI18N
        copyButton.setToolTipText("Copy");
        copyButton.setFocusable(false);
        copyButton.setHideActionText(true);
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(copyButton);

        cutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-cut-5.png"))); // NOI18N
        cutButton.setToolTipText("Cut");
        cutButton.setFocusable(false);
        cutButton.setHideActionText(true);
        cutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(cutButton);

        pasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-paste-3.png"))); // NOI18N
        pasteButton.setToolTipText("Paste");
        pasteButton.setFocusable(false);
        pasteButton.setHideActionText(true);
        pasteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(pasteButton);
        mainToolBar.add(tableOperationsSeparator);

        insertColumnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/insert-table-column.png"))); // NOI18N
        insertColumnButton.setToolTipText("Insert Column");
        insertColumnButton.setFocusable(false);
        insertColumnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertColumnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertColumnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertColumnButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(insertColumnButton);

        insertRowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/insert-table-row.png"))); // NOI18N
        insertRowButton.setToolTipText("Insert Row");
        insertRowButton.setFocusable(false);
        insertRowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertRowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRowButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(insertRowButton);

        removeColumnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/table-column-delete.png"))); // NOI18N
        removeColumnButton.setToolTipText("Remove Column");
        removeColumnButton.setFocusable(false);
        removeColumnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeColumnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeColumnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeColumnButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(removeColumnButton);

        removeRowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/table-row-delete.png"))); // NOI18N
        removeRowButton.setToolTipText("Remove Row");
        removeRowButton.setFocusable(false);
        removeRowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeRowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRowButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(removeRowButton);
        mainToolBar.add(alignmentSeparator);

        alignHorizontalLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-align-left.png"))); // NOI18N
        alignHorizontalLeftButton.setToolTipText("Left");
        alignHorizontalLeftButton.setFocusable(false);
        alignHorizontalLeftButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignHorizontalLeftButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignHorizontalLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignHorizontalLeftButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignHorizontalLeftButton);

        alignHorizontalCenterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-align-center.png"))); // NOI18N
        alignHorizontalCenterButton.setToolTipText("Horizantal Center");
        alignHorizontalCenterButton.setFocusable(false);
        alignHorizontalCenterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignHorizontalCenterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignHorizontalCenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignHorizontalCenterButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignHorizontalCenterButton);

        alignHorizontalRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-align-right.png"))); // NOI18N
        alignHorizontalRightButton.setToolTipText("Right");
        alignHorizontalRightButton.setFocusable(false);
        alignHorizontalRightButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignHorizontalRightButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignHorizontalRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignHorizontalRightButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignHorizontalRightButton);

        alignVerticalTopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/align-vertical-top.png"))); // NOI18N
        alignVerticalTopButton.setToolTipText("Top");
        alignVerticalTopButton.setFocusable(false);
        alignVerticalTopButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignVerticalTopButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignVerticalTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignVerticalTopButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignVerticalTopButton);

        alignVerticalMiddleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/align-text-middle.png"))); // NOI18N
        alignVerticalMiddleButton.setToolTipText("");
        alignVerticalMiddleButton.setFocusable(false);
        alignVerticalMiddleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignVerticalMiddleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignVerticalMiddleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignVerticalMiddleButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignVerticalMiddleButton);

        alignVerticalBottomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/align-vertical-bottom.png"))); // NOI18N
        alignVerticalBottomButton.setToolTipText("Bottom");
        alignVerticalBottomButton.setFocusable(false);
        alignVerticalBottomButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alignVerticalBottomButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alignVerticalBottomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignVerticalBottomButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(alignVerticalBottomButton);
        mainToolBar.add(fontStyleSeparator);

        styleBoldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-bold-4.png"))); // NOI18N
        styleBoldButton.setToolTipText("Bold");
        styleBoldButton.setFocusable(false);
        styleBoldButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        styleBoldButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        styleBoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleBoldButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(styleBoldButton);

        styleItalicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-italic-4.png"))); // NOI18N
        styleItalicButton.setToolTipText("Italic");
        styleItalicButton.setFocusable(false);
        styleItalicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        styleItalicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        styleItalicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleItalicButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(styleItalicButton);

        styleUnderlineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/format-text-underline-4.png"))); // NOI18N
        styleUnderlineButton.setToolTipText("Underline");
        styleUnderlineButton.setFocusable(false);
        styleUnderlineButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        styleUnderlineButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        styleUnderlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleUnderlineButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(styleUnderlineButton);
        mainToolBar.add(sortSeparator);

        sortAscendingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-sort-increase.png"))); // NOI18N
        sortAscendingButton.setToolTipText("Ascending");
        sortAscendingButton.setFocusable(false);
        sortAscendingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sortAscendingButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sortAscendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAscendingButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(sortAscendingButton);

        sortDescendingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/edit-sort-decrease.png"))); // NOI18N
        sortDescendingButton.setToolTipText("Descending");
        sortDescendingButton.setFocusable(false);
        sortDescendingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sortDescendingButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sortDescendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDescendingButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(sortDescendingButton);
        mainToolBar.add(chartSeparator);

        addChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/chart-curve-add.png"))); // NOI18N
        addChartButton.setToolTipText("Add Chart");
        addChartButton.setFocusable(false);
        addChartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addChartButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChartButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(addChartButton);

        editChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/chart-curve-edit.png"))); // NOI18N
        editChartButton.setToolTipText("Edit Chart");
        editChartButton.setFocusable(false);
        editChartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editChartButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editChartButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(editChartButton);

        removeChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/chart-curve-delete.png"))); // NOI18N
        removeChartButton.setToolTipText("Remove Chart");
        removeChartButton.setFocusable(false);
        removeChartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeChartButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChartButtonActionPerformed(evt);
            }
        });
        mainToolBar.add(removeChartButton);

        chartVisibilityToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16x16/office-chart-pie.png"))); // NOI18N
        chartVisibilityToggleButton.setFocusable(false);
        chartVisibilityToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chartVisibilityToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(chartVisibilityToggleButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(mainToolBar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(workbookPanel, gridBagConstraints);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        workbookPanel.newWorkbook();
    }//GEN-LAST:event_newButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        workbookPanel.openFile();
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        workbookPanel.saveFile();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        workbookPanel.undo();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoButtonActionPerformed
        workbookPanel.redo();
    }//GEN-LAST:event_redoButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        workbookPanel.copy();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutButtonActionPerformed
        workbookPanel.cut();
    }//GEN-LAST:event_cutButtonActionPerformed

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        workbookPanel.paste();
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void insertColumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertColumnButtonActionPerformed
        workbookPanel.insertColumn();
    }//GEN-LAST:event_insertColumnButtonActionPerformed

    private void insertRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRowButtonActionPerformed
        workbookPanel.insertRow();
    }//GEN-LAST:event_insertRowButtonActionPerformed

    private void removeColumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeColumnButtonActionPerformed
        workbookPanel.removeColumn();
    }//GEN-LAST:event_removeColumnButtonActionPerformed

    private void removeRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRowButtonActionPerformed
        workbookPanel.removeRow();
    }//GEN-LAST:event_removeRowButtonActionPerformed

    private void alignHorizontalLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignHorizontalLeftButtonActionPerformed
        workbookPanel.alignHorizontalLeft();
    }//GEN-LAST:event_alignHorizontalLeftButtonActionPerformed

    private void alignHorizontalCenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignHorizontalCenterButtonActionPerformed
        workbookPanel.alignHorizontalCenter();
    }//GEN-LAST:event_alignHorizontalCenterButtonActionPerformed

    private void alignHorizontalRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignHorizontalRightButtonActionPerformed
        workbookPanel.alignHorizontalRight();
    }//GEN-LAST:event_alignHorizontalRightButtonActionPerformed

    private void alignVerticalTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignVerticalTopButtonActionPerformed
        workbookPanel.alignVerticalTop();
    }//GEN-LAST:event_alignVerticalTopButtonActionPerformed

    private void alignVerticalMiddleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignVerticalMiddleButtonActionPerformed
        workbookPanel.alignVerticalMiddle();
    }//GEN-LAST:event_alignVerticalMiddleButtonActionPerformed

    private void alignVerticalBottomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignVerticalBottomButtonActionPerformed
        workbookPanel.alignVerticalBottom();
    }//GEN-LAST:event_alignVerticalBottomButtonActionPerformed

    private void styleBoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleBoldButtonActionPerformed
        workbookPanel.styleBold();
    }//GEN-LAST:event_styleBoldButtonActionPerformed

    private void styleItalicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleItalicButtonActionPerformed
        workbookPanel.styleItalic();
    }//GEN-LAST:event_styleItalicButtonActionPerformed

    private void styleUnderlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleUnderlineButtonActionPerformed
        workbookPanel.styleUnderline();
    }//GEN-LAST:event_styleUnderlineButtonActionPerformed

    private void sortAscendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAscendingButtonActionPerformed
        workbookPanel.sort(SortType.ASCENDING);
    }//GEN-LAST:event_sortAscendingButtonActionPerformed

    private void sortDescendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDescendingButtonActionPerformed
        workbookPanel.sort(SortType.DISCENDING);
    }//GEN-LAST:event_sortDescendingButtonActionPerformed

    private void addChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChartButtonActionPerformed
        workbookPanel.addChart();
    }//GEN-LAST:event_addChartButtonActionPerformed

    private void editChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editChartButtonActionPerformed
        workbookPanel.editChart();
    }//GEN-LAST:event_editChartButtonActionPerformed

    private void removeChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChartButtonActionPerformed
        workbookPanel.removeChart();
    }//GEN-LAST:event_removeChartButtonActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChartButton;
    private javax.swing.JButton alignHorizontalCenterButton;
    private javax.swing.JButton alignHorizontalLeftButton;
    private javax.swing.JButton alignHorizontalRightButton;
    private javax.swing.JButton alignVerticalBottomButton;
    private javax.swing.JButton alignVerticalMiddleButton;
    private javax.swing.JButton alignVerticalTopButton;
    private javax.swing.JToolBar.Separator alignmentSeparator;
    private javax.swing.JToolBar.Separator chartSeparator;
    private javax.swing.JToggleButton chartVisibilityToggleButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JToolBar.Separator copyPasteToolBarSeparator;
    private javax.swing.JButton cutButton;
    private javax.swing.JButton editChartButton;
    private javax.swing.JToolBar.Separator fontStyleSeparator;
    private javax.swing.JButton insertColumnButton;
    private javax.swing.JButton insertRowButton;
    private javax.swing.JToolBar mainToolBar;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton pasteButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton removeChartButton;
    private javax.swing.JButton removeColumnButton;
    private javax.swing.JButton removeRowButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton sortAscendingButton;
    private javax.swing.JButton sortDescendingButton;
    private javax.swing.JToolBar.Separator sortSeparator;
    private javax.swing.JButton styleBoldButton;
    private javax.swing.JButton styleItalicButton;
    private javax.swing.JButton styleUnderlineButton;
    private javax.swing.JToolBar.Separator tableOperationsSeparator;
    private javax.swing.JButton undoButton;
    private javax.swing.JToolBar.Separator undoRedoToolBarSeparator;
    private com.gtanalysis.gtexcel.ui.WorkbookPanel workbookPanel;
    // End of variables declaration//GEN-END:variables
	private void initCustom() {
        setWorkbookComponentsVisible(false);
        workbookPanel.addWorkbookListener(new WorkbookListener() {
            @Override
            public void workbookCreated(WorkbookEvent evt) {
                setWorkbookComponentsVisible(true);
            }

            @Override
            public void workbookLoaded(WorkbookEvent evt) {
                setWorkbookComponentsVisible(true);
            }

            @Override
            public void workbookSaved(WorkbookEvent evt) {
            }

            @Override
            public void workbookClosed(WorkbookEvent evt) {
                setWorkbookComponentsVisible(false);
            }
        });
        this.workbookPanel.getWorkbookModel().addPropertyChangeListener("undoEnabled", (PropertyChangeEvent evt) -> {
            firePropertyChange("undoEnabled", !isUndoEnabled(), isUndoEnabled());
            firePropertyChange("redoEnabled", !isRedoEnabled(), isRedoEnabled());
            this.workbookPanel.updateUI();
        });
        this.workbookPanel.getWorkbookModel().addPropertyChangeListener("redoEnabled", (PropertyChangeEvent evt) -> {
            firePropertyChange("undoEnabled", !isUndoEnabled(), isUndoEnabled());
            firePropertyChange("redoEnabled", !isRedoEnabled(), isRedoEnabled());
            this.workbookPanel.updateUI();
        });
    }
    public boolean isUndoEnabled() {
        return this.workbookPanel.isUndoEnabled();
    }

    public boolean isRedoEnabled() {
        return this.workbookPanel.isRedoEnabled();
    }
	private void setWorkbookComponentsVisible(boolean visible) {
        tableOperationsSeparator.setVisible(visible);
        insertColumnButton.setVisible(visible);
        insertRowButton.setVisible(visible);
        removeColumnButton.setVisible(visible);
        removeRowButton.setVisible(visible);
        alignmentSeparator.setVisible(visible);
        alignHorizontalLeftButton.setVisible(visible);
        alignHorizontalCenterButton.setVisible(visible);
        alignHorizontalRightButton.setVisible(visible);
        alignVerticalTopButton.setVisible(visible);
        alignVerticalMiddleButton.setVisible(visible);
        alignVerticalBottomButton.setVisible(visible);
        fontStyleSeparator.setVisible(visible);
        styleBoldButton.setVisible(visible);
        styleItalicButton.setVisible(visible);
        styleUnderlineButton.setVisible(visible);
        sortSeparator.setVisible(visible);
        sortAscendingButton.setVisible(visible);
        sortDescendingButton.setVisible(visible);
        chartSeparator.setVisible(visible);
        addChartButton.setVisible(visible);
        editChartButton.setVisible(visible);
        removeChartButton.setVisible(visible);
        chartVisibilityToggleButton.setVisible(visible);
        undoRedoToolBarSeparator.setVisible(visible);
        undoButton.setVisible(visible);
        redoButton.setVisible(visible);
        
        copyButton.setVisible(visible);
        cutButton.setVisible(visible);
        pasteButton.setVisible(visible);

        // Enable/Disable items
        

    }

}
